export enum PLATFORM_AGGREGATORS {
  YANDEX = 'YANDEX',
  GOOGLE = 'GOOGLE',
  RELAX = 'RELAX',
  TRIPADVISOR = 'TRIPADVISOR',
  CARTE = 'CARTE',
  KOKO = 'KOKO',
}

export const PLATFORM_OPTIONS = [
  { key: PLATFORM_AGGREGATORS.YANDEX, value: PLATFORM_AGGREGATORS.YANDEX.toLowerCase() },
  { key: PLATFORM_AGGREGATORS.GOOGLE, value: PLATFORM_AGGREGATORS.GOOGLE.toLowerCase() },
  { key: PLATFORM_AGGREGATORS.RELAX, value: PLATFORM_AGGREGATORS.RELAX.toLowerCase() },
];

export const DEFAULT_PLATFORM_AGGREGATORS = PLATFORM_AGGREGATORS.YANDEX;

export const FEEDBACKS_LIMIT = 10;
