name: build and deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile --network-timeout 1000000 # will run `yarn install` command
      - name: stop pm2 admin
        run: ./node_modules/pm2/bin/pm2 stop admin
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn install` command
      - name: start pm2 admin
        run: ./node_modules/pm2/bin/pm2 start admin
